import { PDFDocument, rgb, StandardFonts } from "pdf-lib";
import type { DetectionItem } from "./types";
import { PII_TYPE_LABELS } from "./types";

export async function generateReportPdf(
  filename: string,
  totalPages: number,
  detections: DetectionItem[],
  originalPdfBytes: Uint8Array
): Promise<Uint8Array> {
  const kept = detections.filter((d) => d.kept);
  const uniqueTypes = new Map<string, number>();
  let totalOccurrences = 0;
  for (const d of kept) {
    uniqueTypes.set(d.piiType, (uniqueTypes.get(d.piiType) || 0) + d.occurrences.length);
    totalOccurrences += d.occurrences.length;
  }

  // Load the redacted PDF and create a blank report page
  const pdfDoc = await PDFDocument.load(originalPdfBytes);
  const reportPage = pdfDoc.insertPage(0, [612, 792]); // Letter size
  const { width, height } = reportPage.getSize();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const fontSize = 10;
  const darkGray = rgb(0.15, 0.15, 0.15);
  const midGray = rgb(0.4, 0.4, 0.4);
  const blue = rgb(0.23, 0.51, 0.96);

  // Header
  reportPage.drawText("Certificate of Redaction", {
    x: 50,
    y: height - 60,
    size: 22,
    font: fontBold,
    color: darkGray,
  });

  reportPage.drawText("Generated by Redactly", {
    x: 50,
    y: height - 85,
    size: 11,
    font,
    color: blue,
  });

  // Horizontal line
  reportPage.drawLine({
    start: { x: 50, y: height - 100 },
    end: { x: width - 50, y: height - 100 },
    thickness: 1,
    color: rgb(0.85, 0.85, 0.85),
  });

  // Document info
  const infoY = height - 130;
  const infoLineHeight = 20;

  const drawInfoRow = (label: string, value: string, y: number) => {
    reportPage.drawText(label, { x: 50, y, size: fontSize, font: fontBold, color: darkGray });
    reportPage.drawText(value, { x: 200, y, size: fontSize, font, color: darkGray });
  };

  drawInfoRow("Document:", filename, infoY);
  drawInfoRow("Date:", new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), infoY - infoLineHeight);
  drawInfoRow("Pages:", String(totalPages), infoY - infoLineHeight * 2);
  drawInfoRow("PII Categories:", String(uniqueTypes.size), infoY - infoLineHeight * 3);
  drawInfoRow("Total Redacted:", String(totalOccurrences), infoY - infoLineHeight * 4);

  // PII breakdown table
  const tableY = infoY - infoLineHeight * 6;
  reportPage.drawText("Redaction Summary", {
    x: 50,
    y: tableY,
    size: 14,
    font: fontBold,
    color: darkGray,
  });

  // Table header
  const tableTop = tableY - 25;
  reportPage.drawText("PII Type", { x: 50, y: tableTop, size: fontSize, font: fontBold, color: midGray });
  reportPage.drawText("Occurrences", { x: 300, y: tableTop, size: fontSize, font: fontBold, color: midGray });

  let rowY = tableTop - 18;
  const sortedTypes = [...uniqueTypes.entries()].sort((a, b) => b[1] - a[1]);
  for (const [piiType, count] of sortedTypes) {
    if (rowY < 150) break;
    const label = PII_TYPE_LABELS[piiType as keyof typeof PII_TYPE_LABELS] || piiType;
    reportPage.drawText(label, { x: 60, y: rowY, size: fontSize, font, color: darkGray });
    reportPage.drawText(String(count), { x: 310, y: rowY, size: fontSize, font, color: darkGray });
    rowY -= 16;
  }

  // Stamp: "Digitally Redacted" circle
  const cx = width - 120;
  const cy = 200;
  const stampRadius = 55;

  reportPage.drawCircle({
    x: cx,
    y: cy,
    size: stampRadius,
    borderWidth: 2,
    borderColor: rgb(0.23, 0.51, 0.96),
    color: rgb(0.94, 0.97, 1),
  });

  reportPage.drawText("DIGITALLY", {
    x: cx - 35,
    y: cy + 12,
    size: 12,
    font: fontBold,
    color: blue,
  });
  reportPage.drawText("REDACTED", {
    x: cx - 33,
    y: cy - 4,
    size: 12,
    font: fontBold,
    color: blue,
  });
  reportPage.drawText("BY REDACTLY", {
    x: cx - 32,
    y: cy - 20,
    size: 9,
    font,
    color: blue,
  });

  // Disclaimer
  reportPage.drawText(
    "This document was processed by Redactly AI-powered redaction. PII detection was performed by Claude (Anthropic).",
    { x: 50, y: 55, size: 7, font, color: midGray }
  );
  reportPage.drawText(
    "Redactions are visual overlays. For content-stream redaction, upgrade to Pro for PyMuPDF-based processing.",
    { x: 50, y: 42, size: 7, font, color: midGray }
  );
  reportPage.drawText(
    `Report ID: ${crypto.randomUUID()}`,
    { x: 50, y: 29, size: 7, font, color: rgb(0.7, 0.7, 0.7) }
  );

  return await pdfDoc.save();
}
